version: 2
updates:
- directory: /src/UnMango.Audio
  package-ecosystem: nuget
  schedule:
    interval: weekly
  reviewers:
    - UnstoppableMango
  open-pull-requests-limit: 15

- directory: /test/UnMango.Audio.IntegrationTests
  package-ecosystem: nuget
  schedule:
    interval: weekly
  reviewers:
    - UnstoppableMango
  open-pull-requests-limit: 15

- directory: /test/UnMango.Audio.Tests
  package-ecosystem: nuget
  schedule:
    interval: weekly
  reviewers:
    - UnstoppableMango
  open-pull-requests-limit: 15

- directory: /bench/UnMango.Audio.Benchmarks
  package-ecosystem: nuget
  schedule:
    interval: weekly
  reviewers:
    - UnstoppableMango
  open-pull-requests-limit: 15
