coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 5%
        informational: true

comment:
  layout: 'header, diff, flags, components'

component_management:
  individual_components:
    - component_id: core
      name: UnMango.Audio
      paths:
        - src/UnMango.Audio

