name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: |
          dotnet test \
            --no-build \
            --configuration Release \
            --collect:"XPlat Code Coverage" \
            --results-directory "./coverage" \
            --verbosity normal

      - uses: codecov/codecov-action@v3
        with:
          directory: coverage
          files: '**/coverage.cobertura.xml'

      - name: Pack
        run: dotnet pack --no-build --configuration Release --output out

      # TODO: Publish to nuget.org
